package de.voidstack_overload.cardgame.connection;

public enum MessageType {
    ACCOUNT_LOGIN,
    ACCOUNT_LOGIN_ACCEPT,
    ACCOUNT_LOGIN_DENY,

    ACCOUNT_REGISTER,
    ACCOUNT_REGISTER_ACCEPT,
    ACCOUNT_REGISTER_DENY,

    LOBBY_CREATE,
    LOBBY_CREATE_ACCEPT,
    LOBBY_CREATE_DENY,

    LOBBY_JOIN_ACCEPT,
    LOBBY_JOIN_DENY,

    LOBBY_LIST_REPLY,

    GAME_STATE,
    UNKNOWN_CASE,
    ERROR,
    INSUFFICIENT_PERMISSIONS
}
